# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2015-win2012r2'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# some tests are failing on npm@5, downgrade to npm@3
# namely: protect-patch.test.js, wizard-prepare.test.js, wizard-prepublish.test.js
- script: |
    npm i -g npm@^3.10.10
    npm --version
  displayName: 'downgrade npm'

# npm test is configured for Linux, use "tap" command instead
- script: |
    npm run tap
  displayName: 'npm test'
